app:
  name: "bluebell"
  mode: "dev"
  port: 8081
  version: v0.0.1
  start_time: "2020-07-01"
  machine_id: 1
  jwt_expire: 240
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "lihuawei"
  dbname: "bluebell"
  max_open_conns: 20
  max_idle_conns: 10
redis:
  host: "192.168.66.128"
  port: "6379"
  password: ""
  db: 0
  pool_size: 100